# Generated by Django 5.1.1 on 2024-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('Vermelho', 'Vermelho'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Rosa', 'Rosa'), ('Laranja', 'Laranja'), ('Marron', 'Marron')], default='', max_length=10, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande'), ('Extra-Grande', 'Extra-Grande')], default='', max_length=15, verbose_name='Tamanho'),
        ),
    ]
